import os
import subprocess 

include = Dir('#/include')
gmockIncDir = Dir('/home/hurt/tools/gmock/include')
gTestIncDir = Dir('/home/hurt/tools/gmock/gtest/include')

gmockLibDir = Dir('/home/hurt/tools/gmock/build')
gTestLibDir = Dir('/home/hurt/tools/gmock/gtest/build')

picoscopeInclude = Dir('/opt/picoscope/include')
Import('env')
rpathLib = Dir('#/lib')
env['RPATH'] = str(rpathLib)
print env['RPATH']

env.Append(LIBPATH=['#/lib', gmockLibDir, gTestLibDir])
env['CPPPATH'].append(gmockIncDir)
env['CPPPATH'].append(gTestIncDir)

env.Append(LIBPATH=['#/lib'])


env['CPPPATH'].append('/usr/include/python2.7')

env.Append(LIBS=['libpicoscopeInterface', 'ps6404', 'ps6000', 'gmock', 'pthread', 'python2.7', 'ps5444b', 'ps5000a'])

interfaceLib = File('#/lib/libpicoscopeInterface.so')

#test6000 = env.Program('test6000', ['test6000.cc', 'testRunner.cc'])
testGeneric = env.Program('testGeneric', ['testGeneric.cc'])  

