import os

rpathLib = Dir('#/lib')

include = Dir('#/include')
picoscopeInclude = Dir('/opt/picoscope/include')

env = Environment(LIBS=['ps6000'], CCFLAGS=' -ggdb  -std=c++11', CPPPATH=[include, picoscopeInclude], LIBPATH=['#/lib', '/opt/picoscope/lib', '.'])

env.Append(RPATH = str(Dir('#/lib')))


## Generate Root Dictionary File 
cintBuilder = Builder(action = 'rootcint -f $TARGET -c $SOURCES')
env.Append(BUILDERS= {'cint': cintBuilder})

psInterface = env.SharedLibrary('picoscopeInterface', ['picoscopeInterface.cc', 'waveform.cc'])
ps6000Interface = env.SharedLibrary('ps6404', ['ps6000.cc' ])
ps5000aInterface = env.SharedLibrary('ps5444b', ['ps5000a.cc'])
env.Alias('install','/opt/uvahep')

if 'install' in COMMAND_LINE_TARGETS:
    if not os.path.exists('/opt/uvahep'):
        Execute(Mkdir('/opt/uvahep'))
    env.Install('/opt/uvahep/lib', [ps6000Interface, ps5000aInterface, psInterface])
    env.Install('/opt/uvahep/include', ['#/include/waveform.h', '#/include/enums.h', '#/include/picoscopeInterface.h','#/include/ps5000a.h', '#/include/ps6000.h'])
else:
    psInstInterface = env.Install('#/lib', [psInterface])
    env.Install('#/lib', ps6000Interface)
    env.Install('#/lib', ps5000aInterface)
